#!/usr/bin/env bash
# load balanecer haproxy install
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxyORIGINAL.cfg
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend http
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
    balance roundrobin
    server 1026-web-01 34.139.190.16 check
    server 1026-web-02 3.238.201.120 check
EOF
service haproxy restart
