#!/usr/bin/env bash
# Script that displays fizz for multiples of 3 and buzz for multiples of 5
for((n=1;n<=100;n++))
do
    if ((n % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((n % 3 == 0))
    then
        echo "Fizz"
    elif ((n % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$n"
    fi
done
