#!/usr/bin/env bash
# Scriot that displays info about the school file
file="school"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "$file file does not exist"
fi
